### ISSUE TITLE
Issue with ethernet mod on anycube photon

### ISSUE THREAD

**Issue by tadkins92** [Photonsters/photon-ui-mods#10]
Hello, I was wondering if I am missing something on my install for using the ethernet port on back of a cube photon.  I downloaded file and put it on a USB that I have used before. The .logo file doesn't show up at all and the .bin file fails. Any information would be helpful I am using v3.4.1 UI2.6

Thank you

**Comment by X3msnake** [comment]
if the firnware is not loading you most likely own a Fauxton and not s Photon original

if that is the case it has a green anycubic board and this firmware/ui is not compatible.

only solution if you want to use network is to ditch Anycubic board and buy a chitusystems board to replace sorry

**Comment by mhegedusgithub** [comment]
Thx 4 answer,  I had a question in the other section...
Marton
